"""add unit price to order product association table

Revision ID: 608d6be1ba3a
Revises: 4d912276051a
Create Date: 2025-02-08 17:42:03.888046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "608d6be1ba3a"
down_revision: Union[str, None] = "4d912276051a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_associations",
        sa.Column("unit_price", sa.Float(), server_default="0.0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_associations", "unit_price")
    # ### end Alembic commands ###
